### ISSUE TITLE
Enum에 대해 검색 가능한 select 도입

### ISSUE THREAD

**Issue by XiNiHa** [portone-io/sdk-playground.portone.io#30]
지금은 그냥 text input으로 처리하고 있음

**Comment by CirnoV** [comment]
- 기능 구현은 별도의 라이브러리가 없다면 [<datalist>](https://developer.mozilla.org/ko/docs/Web/HTML/Element/datalist) 이용해서 구현하면 될 것 같습니다.
- 혹시 개발자센터 말고 enum 타입으로 해야하는 파라미터들을 정리해둔 곳이 있을까요?

**Comment by XiNiHa** [comment]
> 혹시 개발자센터 말고 enum 타입으로 해야하는 파라미터들을 정리해둔 곳이 있을까요?

딱히 정리가 되어 있진 않지만(...) [여기](https://github.com/portone-io/browser-sdk/tree/main/packages/browser-sdk/src/v2)의 타입들을 보시면 될 것 같습니다!
