### ISSUE TITLE
배열 입력 기능 추가

### ISSUE THREAD

**Issue by XiNiHa** [portone-io/sdk-playground.portone.io#31]
지금은 배열 형태의 파라미터를 입력받을 수 없어서 products 같은 파라미터를 UI 상에서 보여주지 못하고 있음

**Comment by CirnoV** [comment]
![image](https://github.com/portone-io/sdk-playground.portone.io/assets/17797795/5e8bf504-774a-41a0-94ea-4dcab54584eb)

배열 형태는 이런식으로 추가/삭제 버튼 만들어서 입력하도록 구현하면 좋을 것 같습니다

**Comment by XiNiHa** [comment]
좋네요 :+1:  대신 배열 안에 객체가 들어갈 수도 있다는 점도 참고해서 구현해주세요!

**Comment by XiNiHa** [comment]
Closed in #33
