### ISSUE TITLE
V2 결제수단별 필드 입력 지원

### ISSUE THREAD

**Issue by XiNiHa** [portone-io/sdk-playground.portone.io#32]
V2에서는 사용하는 결제수단에 따라서 card / virtualAccount / giftCertificate 등의 객체 필드가 추가되는데, 해당 필드에 대한 입력을 현재 raw JSON으로밖에 지원하고 있지 않음

**Comment by CirnoV** [comment]
![image](https://github.com/portone-io/sdk-playground.portone.io/assets/17797795/3265842e-6b3e-4fe1-b1bb-65c19a6a1123)

raw JSON 대신에 기존 FieldControl을 활용해서 입력할 수 있도록 해봤습니다.

**Comment by XiNiHa** [comment]
Closed in #33
